### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by JadenGuo** [01org/virtual-storage-manager#562]
I try many times and this error happend every time,can you give me some advice?
`Connection to 172.21.107.104 closed.
++ ssh -t cephuser@172.21.107.104 'cluster_manifest|grep error|wc -l'
Connection to 172.21.107.104 closed.
+ is_cluster_manifest_error=$'0\r'
+ '[' $'0\r' -gt 0 ']'
: integer expression expected
+ [[ -n '' ]]
+ ssh -t cephuser@172.21.107.104 'sudo -E vsm-controller'

Traceback (most recent call last):
  File "/usr/local/bin/getip", line 147, in <module>
    res = iper.get_controller_ip()
  File "/usr/local/bin/getip", line 83, in get_controller_ip
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
`

**Comment by flyingfish007** [comment]
@JadenGuo 
Before you run the install.sh script to deploy the vsm, did you change the management_addr, ceph_public_addr and ceph_cluster_addr of cluster.manifest from the folder(manifest/<ip or hostname of vsm controller>/). You should change them based on your real network.

**Comment by JadenGuo** [comment]
I have done all thosr work already

**Comment by flyingfish007** [comment]
If possible, can you post your cluster.manifest file and give the result of "hostname -I" on your controller node which node you run the install.sh script.

**Comment by JadenGuo** [comment]
cluster.manifest:
`[storage_class]`
`10krpm_sas`
`7200_rpm_sata`
`ssd`
`#ssd_cached_7200rpm_sata`
`#ssd_cached_10krpm_sas`

`[storage_group]`
`#format: [storage group name]  [user friendly storage group name] [storage class]`
`performance       Performance_Disk       10krpm_sas`
`capacity          Economy_Disk           7200_rpm_sata`
`high_performance  High_Performance       ssd`
`#value_performance High_Performance_Disk_with_ssd_cached_Acceleration ssd_cached_10krpm_sas`
`#value_capacity    Capacity_Disk_with_ssd_cached_Acceleration ssd_cached_7200rpm_sata`
`[cluster]`
`cluster_a`

`[file_system]`
`xfs`

`[management_addr]`
`172.21.107.0/24`

`[ceph_public_addr]`
`172.21.107.0/24`

`[ceph_cluster_addr]`
`192.168.1.0/24`

`[settings]`
`storage_group_near_full_threshold  65`
`storage_group_full_threshold  85`
`ceph_near_full_threshold  75`
`ceph_full_threshold  90`
`pg_count_factor 100`
`heartbeat_interval 5`
`osd_heartbeat_interval 10`
`osd_heartbeat_grace 10`
`disk_near_full_threshold 75`
`disk_full_threshold 90`
`osd_pool_default_size 3`
`[ec_profiles]`
`#format: [profile-name] [path-to-plugin] [plugin-name] [pg_num value] [json format key/value]`
`#the key/value strings should not have spaces`
`default_profile  /usr/lib64/ceph/erasure-code  jerasure  3  {"k":2,"m":1,"technique":"reed_sol_van"}`
`#profile_name2  /usr/lib64/ceph/erasure-code  jerasure  6  {"k":4,"m":2,"technique":"reed_sol_van"}`

`[cache_tier_defaults]`
`ct_hit_set_count 1`
`ct_hit_set_period_s 3600`
`ct_target_max_mem_mb 1000000`
`ct_target_dirty_ratio 0.4`
`ct_target_full_ratio 0.8`
`ct_target_max_objects 1000000`
`ct_target_min_flush_age_m 10`
`ct_target_min_evict_age_m 20`
and my hosts are like this:

`172.21.107.49   ceph1`
`172.21.107.50   ceph2`
`172.21.107.51   ceph3`
`172.21.107.104  ceph-vsm`

**Comment by flyingfish007** [comment]
@JadenGuo Thanks for your information provided.
1. What's the result of command "**hostname -I**" on your controller node.
2. And also, which **release of vsm** do you use or whether you build the packages from the source code.

**Comment by JadenGuo** [comment]
the result of hostname -i is:
127.0.1.1
I and using version 2.1.0-336

**Comment by flyingfish007** [comment]
"hostname -I", the capital i.
If your result of "hostname -I" doesn't include 172.21.107.104, maybe it is the reason why it come into error. The script of "getip" will comparethe result of “hostname -I” with "ceph_public_addr" of cluster.manifest.  So next step is to find why not including 172.21.107.104.

**Comment by JadenGuo** [comment]
I know the reason,thanks so much!

**Comment by JadenGuo** [comment]
one more error I found.
`+ MYSQL_ROOT_PW_ARG=`
`+ echo 'SELECT 1;'`
`+ mysql -uroot -p5f2db3a80cc3455f6df3 -h172.21.107.49`
`ERROR 1045 (28000): Access denied for user 'root'@'ceph1' (using password: YES)`
`+ echo 'Failed to connect to the MySQL server.  Please check your root user credentials.'`
`Failed to connect to the MySQL server.  Please check your root user credentials.`
`+ exit 1`

**Comment by ywang19** [comment]
the /etc/hosts should be changed to include controller and agents IP before running install.sh


在 2016年9月21日，下午1:03，JadenGuo <notifications@github.com> 写道：

the result of hostname -i is:
127.0.1.1
I and using version 2.1.0-336

**Comment by flyingfish007** [comment]
@JadenGuo 
I think that the issue maybe occurs because of the interruption when the script is running to handle with the mysql. Try to remove the mysql related packages and run the install.sh script again.

**Comment by Noc-Net** [comment]
Sorry for hijack this thread. I have issue also on install. I'm using ver 2.2.51 and ceph hammer (centos 7).
Below is error:
--> Finished Dependency Resolution
Error: Package: vsm-dashboard-2.2.0-521.noarch (vsmrepo)
           Requires: python-django-openstack-auth
Error: Package: python-vsmclient-2.2.0-521.noarch (vsmrepo)
           Requires: python-httplib2
Error: Package: vsm-dashboard-2.2.0-521.noarch (vsmrepo)
           Requires: python-ordereddict
Error: Package: vsm-dashboard-2.2.0-521.noarch (vsmrepo)
           Requires: python-httplib2
Error: Package: vsm-2.2.0-521.noarch (vsmrepo)
           Requires: python-kombu
Error: Package: python-cinderclient-1.1.1-1.el7.centos.noarch (vsmdeprepo)
           Requires: python-simplejson
Error: Package: vsm-dashboard-2.2.0-521.noarch (vsmrepo)
           Requires: python-django-compressor
Error: Package: vsm-2.2.0-521.noarch (vsmrepo)
           Requires: python-psutil
Error: Package: 1:python-novaclient-2.20.0-1.el7.centos.noarch (vsmdeprepo)
           Requires: python-keyring
Error: Package: 1:python-novaclient-2.20.0-1.el7.centos.noarch (vsmdeprepo)
           Requires: python-iso8601
Error: Package: 1:python-novaclient-2.20.0-1.el7.centos.noarch (vsmdeprepo)
           Requires: python-simplejson
Error: Package: vsm-dashboard-2.2.0-521.noarch (vsmrepo)
           Requires: python-jsonschema
Error: Package: vsm-2.2.0-521.noarch (vsmrepo)
           Requires: python-migrate
Error: Package: vsm-dashboard-2.2.0-521.noarch (vsmrepo)
           Requires: python-cmd2
Error: Package: vsm-2.2.0-521.noarch (vsmrepo)
           Requires: python-routes
Error: Package: vsm-dashboard-2.2.0-521.noarch (vsmrepo)
           Requires: python-keyring
Error: Package: 1:python-keystoneclient-0.11.1-1.el7.centos.noarch (vsmdeprepo)
           Requires: python-keyring
Error: Package: vsm-2.2.0-521.noarch (vsmrepo)
           Requires: python-eventlet
Error: Package: vsm-2.2.0-521.noarch (vsmrepo)
           Requires: python-stevedore
Error: Package: vsm-dashboard-2.2.0-521.noarch (vsmrepo)
           Requires: python-versiontools
Error: Package: vsm-2.2.0-521.noarch (vsmrepo)
           Requires: python-paste-deploy
Error: Package: vsm-dashboard-2.2.0-521.noarch (vsmrepo)
           Requires: python-django-appconf
Error: Package: vsm-dashboard-2.2.0-521.noarch (vsmrepo)
           Requires: python-cliff
Error: Package: vsm-2.2.0-521.noarch (vsmrepo)
           Requires: python-pbr
Error: Package: vsm-2.2.0-521.noarch (vsmrepo)
           Requires: python-ordereddict
Error: Package: 1:python-keystoneclient-0.11.1-1.el7.centos.noarch (vsmdeprepo)
           Requires: python-iso8601 >= 0.1.4
Error: Package: 2:python-oslo-config-1.4.0-1.el7.centos.noarch (vsmdeprepo)
           Requires: python-stevedore
Error: Package: vsm-2.2.0-521.noarch (vsmrepo)
           Requires: python-anyjson
Error: Package: 1:python-keystoneclient-0.11.1-1.el7.centos.noarch (vsmdeprepo)
           Requires: python-stevedore
Error: Package: vsm-dashboard-2.2.0-521.noarch (vsmrepo)
           Requires: python-django
Error: Package: vsm-dashboard-2.2.0-521.noarch (vsmrepo)
           Requires: python-django-horizon
Error: Package: vsm-dashboard-2.2.0-521.noarch (vsmrepo)
           Requires: python-iso8601
Error: Package: vsm-2.2.0-521.noarch (vsmrepo)
           Requires: python-iso8601
Error: Package: python-oslo-utils-1.0.0-1.el7.centos.noarch (vsmdeprepo)
           Requires: python-iso8601
Error: Package: vsm-dashboard-2.2.0-521.noarch (vsmrepo)
           Requires: python-warlock
Error: Package: vsm-2.2.0-521.noarch (vsmrepo)
           Requires: python-amqplib
Error: Package: vsm-dashboard-2.2.0-521.noarch (vsmrepo)
           Requires: python-simplejson
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Any advice?

**Comment by flyingfish007** [comment]
@Noc-Net Have you set the epel repo on your vsm controller node manually?
BTW: You must set the epel and ceph repo by yourself on vsm controller node manually.

**Comment by Noc-Net** [comment]
Yeah, i have set it. Now get others error.

--> Processing Dependency: python-jsonpointer for package: python-jsonpatch-1.2-3.el7.centos.noarch
--> Running transaction check
---> Package python-django-openstack-auth.noarch 0:1.2.0-2.el7 will be installed
--> Processing Dependency: python-keystoneclient >= 1:1.1.0 for package: python-django-openstack-auth-1.2.0-2.el7.noarch
---> Package python-jsonpointer.noarch 0:1.9-2.el7 will be installed
--> Finished Dependency Resolution
Error: Package: python-django-openstack-auth-1.2.0-2.el7.noarch (vsmrepo)
           Requires: python-keystoneclient >= 1:1.1.0
           Installed: 1:python-keystoneclient-0.11.1-1.el7.centos.noarch (@vsmdeprepo)
               python-keystoneclient = 1:0.11.1-1.el7.centos
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

If i using higher version from 1.1, it will affect others dependency.

**Comment by Noc-Net** [comment]
I adding repo from openstack-liberty. At the end getting this error:
Traceback (most recent call last):
  File "/usr/local/bin/cluster_manifest", line 21, in <module>
    from vsm.manifest.parser import ManifestParser
  File "/usr/lib/python2.7/site-packages/vsm/manifest/__init__.py", line 22, in <module>
    from vsm.manifest import config
  File "/usr/lib/python2.7/site-packages/vsm/manifest/config.py", line 26, in <module>
    from vsm import exception
  File "/usr/lib/python2.7/site-packages/vsm/exception.py", line 27, in <module>
    from oslo.config import cfg
ImportError: No module named config

**Comment by Noc-Net** [comment]
This part need be adjust.

From this:

function download_dependencies() {
    if [[ ! -d $REPO_PATH ]]; then
        mkdir -p $REPO_PATH
        cd $REPO_PATH
        for i in `cat $TOPDIR/rpms.lst`; do
            wget https://github.com/01org/vsm-dependencies/raw/$DEPENDENCE_BRANCH/centos7/$i
        done
        cd $TOPDIR
    elif [[ -d $REPO_PATH ]] && [[ $IS_CHECK_DEPENDENCE_PACKAGE == True ]]; then
        cd $REPO_PATH
        for i in `cat $TOPDIR/rpms.lst`; do
            pkg_name=${i%%_*}_
            if [[ `ls |grep $pkg_name|wc -l` -eq 0 ]]; then
                wget https://github.com/01org/vsm-dependencies/raw/$DEPENDENCE_BRANCH/centos7/$i
            else
                rm $pkg_name*
                wget https://github.com/01org/vsm-dependencies/raw/$DEPENDENCE_BRANCH/centos7/$i
            fi
        done
        $SUDO rm -rf *.rpm.*
        cd $TOPDIR
    fi
}

To this:

function download_dependencies() {
    if [[ ! -d $REPO_PATH ]]; then
        mkdir -p $REPO_PATH
        cd $REPO_PATH
        for i in `cat $TOPDIR/rpms.lst`; do
            wget https://github.com/01org/vsm-dependencies/raw/$DEPENDENCE_BRANCH/centos7/$i
        done
        cd $TOPDIR
    elif [[ -d $REPO_PATH ]] && [[ $IS_CHECK_DEPENDENCE_PACKAGE == True ]]; then
        cd $REPO_PATH
        for i in `cat $TOPDIR/rpms.lst`; do
            pkg_name=${i%%_*}_
            if [[ `ls |grep $pkg_name|wc -l` -eq 0 ]]; then
                wget https://github.com/01org/vsm-dependencies/tree/master/repo/$i
            else
                rm $pkg_name*
                wget https://github.com/01org/vsm-dependencies/tree/master/repo/$i
            fi
        done
        $SUDO rm -rf *.rpm.*
        cd $TOPDIR
    fi
}

Or else it getting error.
